interface Env {
	DB: D1Database
	CORS_ORIGIN: string
	FIREBASE_PROJECT_ID: string
	FIREBASE_CLIENT_EMAIL: string
	FIREBASE_PRIVATE_KEY: string
	STRIPE_SECRET_KEY: string
	STRIPE_WEBHOOK_SECRET: string
}
